#!/usr/bin/env bash
#
# AiNxt SDLC CLI setup — standalone, re-runnable at any time.
#
#   ./sdlc-setup.sh
#
# Enables the SDLC pipeline's CLI engine (the "sdlc-worker" container) as an
# add-on to an already-running AiNxt install, the same way kb-setup.sh adds
# the Knowledge Base. Two things live under bin/ once this finishes:
#
#   bin/ainxt         the native ainxt CLI binary, fetched from GitHub
#                     Releases (npci/ainxt-cli) for the
#                     ARCHITECTURE THE GATEWAY CONTAINER RUNS, not this
#                     host's OS/arch — the binary only ever executes inside
#                     the Linux sdlc-worker container (docker-compose.yml
#                     bind-mounts it to /usr/local/bin/ainxt), so a
#                     Mac/Windows host binary on PATH here would silently
#                     fail to run there. Never committed (see .gitignore).
#
#   bin/config.toml   generated FRESH on every run from whichever LLM
#                     provider key is currently in .env (same priority
#                     ANTHROPIC_API_KEY > OPENAI_API_KEY > GEMINI_API_KEY >
#                     Ollama that choose_provider() in install.sh uses).
#                     Re-run this script any time you change providers in
#                     .env. If bin/config.toml already exists AND was not
#                     generated by this script (no marker comment on line
#                     1), it is left alone — that means a human hand-wrote
#                     it (see bin/config.toml.example) and this script must
#                     not clobber it.
#
# Self-contained on purpose, same rationale as kb-setup.sh: duplicates a
# small number of helpers from install.sh rather than sourcing it, so this
# keeps working standalone long after install.sh ran, with no dependency on
# it having been run first (beyond the base app already being up, which is
# what makes .env and the ainxt-enterprise:local image exist).
#
# Platform notes: this is a bash script — on Windows it must be run from a
# WSL2 shell with Docker Desktop's WSL integration enabled, exactly like
# install.sh and kb-setup.sh (see README.md's Windows setup section). It
# avoids bash-4+-only syntax (associative arrays, ${var,,}, etc.) so it also
# runs correctly under macOS's stock bash 3.2, and looks for whichever of
# sha256sum (Linux) / shasum (macOS) is present rather than assuming one.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

# ── Colors / helpers (mirrors install.sh / kb-setup.sh) ─────────────────────
if [[ -e /dev/tty ]]; then TTY=/dev/tty; else TTY=""; fi

if [[ -t 1 ]]; then
  B=$'\033[1m'; DIM=$'\033[2m'; R=$'\033[0m'
  GRN=$'\033[32m'; YLW=$'\033[33m'; RED=$'\033[31m'; CYN=$'\033[36m'
else
  B=""; DIM=""; R=""; GRN=""; YLW=""; RED=""; CYN=""
fi

say()  { printf '%s\n' "$*"; }
step() { printf '\n%s==>%s %s%s%s\n' "$CYN" "$R" "$B" "$*" "$R"; }
ok()   { printf '  %s✓%s %s\n' "$GRN" "$R" "$*"; }
warn() { printf '  %s!%s %s\n' "$YLW" "$R" "$*"; }
die()  { printf '\n  %s✗ %s%s\n\n' "$RED" "$*" "$R" >&2; exit 1; }

# ── Prerequisites ─────────────────────────────────────────────────────────────
[[ -f .env ]] || die \
"No .env found in $(pwd).
  Run ./install.sh first — it creates .env and starts the base app.
  SDLC setup is an add-on to an already-running install, not a
  replacement for it."

command -v docker >/dev/null 2>&1 || die "Docker is required but was not found."
if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  die "Docker Compose was not found. Install Docker Desktop, or the 'docker-compose-plugin' package."
fi
command -v curl >/dev/null 2>&1 || die "curl is required but was not found."
PYBIN="$(command -v python3 || command -v python || echo python3)"

# Cross-platform SHA-256: Linux ships sha256sum, macOS ships shasum.
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die "Neither sha256sum nor shasum was found — cannot verify the downloaded binary."
  fi
}

set_env() {
  local k="$1" v="$2"
  if grep -qE "^${k}=" .env; then
    "$PYBIN" - "$k" "$v" <<'PY'
import re, sys
k, v = sys.argv[1], sys.argv[2]
s = open('.env').read()
s = re.sub(rf'^{re.escape(k)}=.*$', f'{k}={v}', s, flags=re.M)
open('.env','w').write(s)
PY
  else
    printf '%s=%s\n' "$k" "$v" >> .env
  fi
}

step "SDLC CLI setup"
say "  Enables the SDLC pipeline's coding-agent engine (the sdlc-worker container)."

# ── 0. Ensure required .env values exist ────────────────────────────────────
# Fixed values (service key, gateway URL) are the same for every install and
# have no compose-side default (docker-compose.yml falls back to blank), so
# they're generated/written here automatically. Claude model IDs DO have a
# blank compose fallback too, and core/model_registry.py's guard fails closed
# on blank (see patches/0011), so a fresh install needs *something* there to
# work out of the box — pre-filled with sane defaults, but they're only a
# placeholder, not a correctness guarantee. Flagged again once setup finishes.
MODELS_DEFAULTED=""

env_get() {
  # Several keys this script checks (AINXT_PLATFORM_SERVICE_API_KEYS,
  # SDLC_CLI_GATEWAY_URL) aren't in .env.example at all on older installs, so
  # grep legitimately finds no match. Under `set -o pipefail` that failure
  # exit status propagates through head/cut — harmless in a `[[ -z "$(...)" ]]`
  # test, but fatal (silently, no error message) when the result feeds a
  # bare assignment like `x="$(env_get K)"`, since `set -e` treats that
  # assignment's exit status as the substitution's. The `|| true` neutralizes
  # it so "key not present" and "key present but blank" both just come back empty.
  grep -E "^${1}=" .env 2>/dev/null | head -1 | cut -d= -f2- || true
}

ensure_sdlc_env() {
  if [[ -z "$(env_get SDLC_CLI_GATEWAY_URL)" ]]; then
    set_env SDLC_CLI_GATEWAY_URL "http://gateway:8000/ainxt/v1/api/v1/messages"
    ok "SDLC_CLI_GATEWAY_URL set in .env (fixed — the gateway's internal Anthropic-compat endpoint)"
  fi

  local svc_key
  svc_key="$(env_get SDLC_SERVICE_API_KEY)"
  if [[ -z "$svc_key" ]]; then
    svc_key="$("$PYBIN" -c 'import secrets; print(secrets.token_hex(32))')"
    set_env SDLC_SERVICE_API_KEY "$svc_key"
    ok "SDLC_SERVICE_API_KEY generated"
  fi

  # AINXT_PLATFORM_SERVICE_API_KEYS is a comma-separated allowlist shared by
  # other products (routers/messages_compat_router.py) — append rather than
  # overwrite, in case other keys are already listed there.
  local platform_keys
  platform_keys="$(env_get AINXT_PLATFORM_SERVICE_API_KEYS)"
  if [[ -z "$platform_keys" ]]; then
    set_env AINXT_PLATFORM_SERVICE_API_KEYS "$svc_key"
    ok "AINXT_PLATFORM_SERVICE_API_KEYS set to match SDLC_SERVICE_API_KEY"
  elif [[ ",${platform_keys}," != *",${svc_key},"* ]]; then
    set_env AINXT_PLATFORM_SERVICE_API_KEYS "${platform_keys},${svc_key}"
    ok "SDLC_SERVICE_API_KEY appended to AINXT_PLATFORM_SERVICE_API_KEYS"
  fi

  # Only pre-fill Claude model IDs when Anthropic is actually the configured
  # provider — matches render_config_toml()'s provider priority below.
  if [[ -n "$(env_get ANTHROPIC_API_KEY)" ]]; then
    if [[ -z "$(env_get CLAUDE_PRIMARY_MODEL)" ]]; then
      set_env CLAUDE_PRIMARY_MODEL "claude-sonnet-4-6"
      MODELS_DEFAULTED=1
    fi
    if [[ -z "$(env_get CLAUDE_HAIKU)" ]]; then
      set_env CLAUDE_HAIKU "claude-sonnet-4-6"
      MODELS_DEFAULTED=1
    fi
    if [[ -z "$(env_get CLAUDE_OPUS_MODEL)" ]]; then
      set_env CLAUDE_OPUS_MODEL "claude-opus-4-7"
      MODELS_DEFAULTED=1
    fi
    if [[ -n "$MODELS_DEFAULTED" ]]; then
      ok "Claude model IDs defaulted in .env — verify these once setup finishes"
    fi
  fi
}

ensure_sdlc_env

# ── 1. Fetch the ainxt binary (GitHub Releases only) ────────────────────────
REPO="npci/ainxt-cli"

# The binary must match the GATEWAY CONTAINER's architecture, not this
# host's — it only ever runs inside sdlc-worker (same image/arch as
# gateway). Ask Docker directly rather than trusting `uname -m` here, since
# a Mac host can build/run amd64 containers under emulation and vice versa.
docker_arch() {
  local img_arch=""
  img_arch="$(docker image inspect ainxt-enterprise:local --format '{{.Architecture}}' 2>/dev/null || true)"
  if [[ -z "$img_arch" ]]; then
    # Callers capture this function's stdout ($(docker_arch)) as the
    # resolved arch string — these two lines MUST go to stderr, or they'd
    # get captured as part of that value instead of the real answer.
    warn "ainxt-enterprise:local image not found yet — falling back to this host's architecture." >&2
    warn "Build the gateway image first (./install.sh) for an authoritative answer." >&2
    case "$(uname -m)" in
      arm64|aarch64) img_arch="arm64" ;;
      *)             img_arch="amd64" ;;
    esac
  fi
  case "$img_arch" in
    arm64)  echo "aarch64" ;;
    amd64)  echo "x86_64"  ;;
    *)      die "Unrecognized container architecture '$img_arch' — no known ainxt release for it." ;;
  esac
}

# Minimal GitHub REST call. $2 (optional) is a bearer token.
gh_api() {
  local path="$1" token="${2:-}"
  if [[ -n "$token" ]]; then
    curl -fsSL -H "Authorization: Bearer $token" -H "Accept: application/vnd.github+json" \
      "https://api.github.com${path}"
  else
    curl -fsSL -H "Accept: application/vnd.github+json" "https://api.github.com${path}"
  fi
}

fetch_ainxt_binary() {
  local arch; arch="$(docker_arch)"
  local pattern="ainxt-*-linux-${arch}"
  say "  ${DIM}Target: linux-${arch} (matches the gateway container)${R}"

  local token="${SDLC_CLI_GH_TOKEN:-}"
  local release_json=""
  release_json="$(gh_api "/repos/${REPO}/releases/latest" "$token" 2>/dev/null || true)"

  if [[ -z "$release_json" ]]; then
    if [[ -n "$token" ]]; then
      die "Could not reach ${REPO}'s releases even with SDLC_CLI_GH_TOKEN set — check the token has access to this repo."
    fi
    warn "${REPO} did not respond to an unauthenticated request — it may be private."
    if [[ -n "$TTY" ]]; then
      printf '  Paste a GitHub token with access to %s (hidden, Enter to abort): ' "$REPO" > "$TTY"
      read -rs token < "$TTY" || token=""
      printf '\n' > "$TTY"
    fi
    [[ -z "$token" ]] && die "No token provided — cannot fetch the ainxt binary. Place it at bin/ainxt (linux-${arch}) yourself, or set SDLC_CLI_GH_TOKEN in .env and re-run."
    release_json="$(gh_api "/repos/${REPO}/releases/latest" "$token")" \
      || die "Still could not reach ${REPO} with that token."
    set_env SDLC_CLI_GH_TOKEN "$token"
    ok "token saved to .env as SDLC_CLI_GH_TOKEN — future runs won't ask again"
  fi

  # Resolve the binary + its .sha256 sibling asset from the release JSON.
  # `python3 -` reads the SCRIPT from stdin, so the release JSON (also
  # stdin-shaped) has to arrive a different way — write the parser to a real
  # temp file instead and keep stdin free for the JSON payload.
  local parser="bin/.ainxt-resolve.py"
  cat > "$parser" <<'PY'
import fnmatch, json, sys
pattern = sys.argv[1]
data = json.load(sys.stdin)
bin_asset = sha_asset = None
for a in data.get("assets", []):
    name = a["name"]
    if name.endswith(".sha256"):
        if fnmatch.fnmatch(name[:-len(".sha256")], pattern):
            sha_asset = a
    elif fnmatch.fnmatch(name, pattern):
        bin_asset = a
if not bin_asset:
    sys.exit(1)
print(data.get("tag_name", ""))
print(bin_asset["name"])
print(bin_asset["id"])
print(bin_asset["browser_download_url"])
if sha_asset:
    print(sha_asset["name"])
    print(sha_asset["id"])
    print(sha_asset["browser_download_url"])
PY
  local resolved
  resolved="$("$PYBIN" "$parser" "$pattern" <<<"$release_json")"
  local resolve_rc=$?
  rm -f "$parser"
  [[ $resolve_rc -eq 0 ]] || die "No release asset matching '${pattern}' was found in ${REPO}'s latest release."

  local tag bin_name bin_id bin_url sha_name sha_id sha_url
  tag="$(sed -n '1p' <<<"$resolved")"
  bin_name="$(sed -n '2p' <<<"$resolved")"
  bin_id="$(sed -n '3p' <<<"$resolved")"
  bin_url="$(sed -n '4p' <<<"$resolved")"
  sha_name="$(sed -n '5p' <<<"$resolved")"
  sha_id="$(sed -n '6p' <<<"$resolved")"
  sha_url="$(sed -n '7p' <<<"$resolved")"

  ok "resolved ${bin_name} (${tag})"

  local tmp_bin="bin/.ainxt.download"
  download_asset() {
    local id="$1" url="$2" out="$3"
    if [[ -n "$token" ]]; then
      curl -fsSL -H "Authorization: Bearer $token" -H "Accept: application/octet-stream" \
        "https://api.github.com/repos/${REPO}/releases/assets/${id}" -o "$out"
    else
      curl -fsSL "$url" -o "$out"
    fi
  }

  download_asset "$bin_id" "$bin_url" "$tmp_bin" || die "Download of ${bin_name} failed."
  ok "downloaded ${bin_name}"

  if [[ -n "$sha_id" ]]; then
    local tmp_sha="bin/.ainxt.sha256"
    download_asset "$sha_id" "$sha_url" "$tmp_sha" || die "Download of ${sha_name} failed."
    local expected actual
    expected="$(awk '{print $1}' "$tmp_sha")"
    actual="$(sha256_of "$tmp_bin")"
    rm -f "$tmp_sha"
    if [[ "$expected" != "$actual" ]]; then
      rm -f "$tmp_bin"
      die "Checksum mismatch for ${bin_name} — expected ${expected}, got ${actual}. Refusing to install it."
    fi
    ok "checksum verified"
  else
    warn "no .sha256 asset found for ${bin_name} — could not verify its checksum."
    warn "Always verify a downloaded binary's checksum before trusting it."
  fi

  chmod 755 "$tmp_bin"
  mv "$tmp_bin" bin/ainxt
  ok "bin/ainxt installed (${tag}, linux-${arch})"
}

if [[ -f bin/ainxt ]] && file bin/ainxt 2>/dev/null | grep -qi "ELF.*$(docker_arch | sed 's/x86_64/x86-64/')"; then
  ok "bin/ainxt already present and matches the container architecture — skipping download"
  say "  ${DIM}Force a re-fetch: rm bin/ainxt && ./sdlc-setup.sh${R}"
else
  fetch_ainxt_binary
fi

# ── 2. Render bin/config.toml from whichever provider is in .env ───────────
GENERATED_MARKER="# GENERATED by sdlc-setup.sh — edits here do not survive a re-run; edit .env instead."

render_config_toml() {
  # Callers capture this function's stdout (result="$(render_config_toml)")
  # as NONE / a provider name / empty — every diagnostic line below MUST go
  # to stderr, or it becomes part of that captured value instead.
  if [[ -f bin/config.toml ]] && ! head -1 bin/config.toml | grep -qF "$GENERATED_MARKER"; then
    warn "bin/config.toml exists and was not generated by this script — leaving it alone." >&2
    say "  ${DIM}(no marker comment on line 1 — looks hand-written, per bin/config.toml.example)${R}" >&2
    return 0
  fi

  "$PYBIN" - "$GENERATED_MARKER" <<'PY'
import re, sys

marker = sys.argv[1]
env = {}
with open(".env", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip()

def first_nonempty(*keys):
    for k in keys:
        v = env.get(k, "")
        if v:
            return v
    return ""

anthropic_key = env.get("ANTHROPIC_API_KEY", "")
openai_key    = env.get("OPENAI_API_KEY", "")
gemini_key    = env.get("GEMINI_API_KEY", "")

if anthropic_key:
    model = first_nonempty("CLAUDE_PRIMARY_MODEL") or "claude-sonnet-4-6"
    body = f'''[model.sdlc-model]
model = "{model}"
base_url = "https://api.anthropic.com/v1"
name = "Claude (SDLC)"
api_backend = "messages"
context_window = 200000

[model.sdlc-model.extra_headers]
x-api-key = "{anthropic_key}"
anthropic-version = "2023-06-01"
'''
    provider = "anthropic"
elif openai_key:
    model = first_nonempty("OPENAI_CODING_MODEL") or "gpt-5.4"
    body = f'''[model.sdlc-model]
model = "{model}"
base_url = "https://api.openai.com/v1"
name = "GPT (SDLC)"
api_key = "{openai_key}"
context_window = 128000
'''
    provider = "openai"
elif gemini_key:
    model = first_nonempty("GEMINI_TEXT_MODEL") or "gemini-3.5-flash"
    body = f'''# UNVERIFIED: see bin/config.toml.example's Gemini note.
[model.sdlc-model]
model = "{model}"
base_url = "https://generativelanguage.googleapis.com/v1beta/openai"
name = "Gemini (SDLC)"
api_key = "{gemini_key}"
context_window = 1000000
'''
    provider = "gemini"
elif env.get("PROVIDER", "").lower() == "ollama" or env.get("OLLAMA_MODEL"):
    try:
        import json as _json
        model = _json.load(open("config/ollama_model_suggestions.json"))["suggestions"][0]["name"]
    except Exception:
        model = "llama3.2"
    body = f'''[model.sdlc-model]
model = "{model}"
base_url = "http://ollama:11434/v1"
name = "Ollama (SDLC)"
api_key = "local-placeholder"
context_window = 8192
'''
    provider = "ollama"
else:
    provider = None

if provider is None:
    print("NONE")
else:
    with open("bin/config.toml", "w", encoding="utf-8") as f:
        f.write(marker + "\n\n[models]\ndefault = \"sdlc-model\"\n\n" + body)
    print(provider)
PY
}

result="$(render_config_toml)"
case "$result" in
  NONE)
    warn "No LLM provider is configured in .env (ANTHROPIC_API_KEY / OPENAI_API_KEY / GEMINI_API_KEY / Ollama)."
    warn "SDLC needs one to run. Add a key to .env and re-run ./sdlc-setup.sh, or copy"
    warn "bin/config.toml.example to bin/config.toml yourself and fill in a custom endpoint."
    ;;
  "")
    ;; # bin/config.toml already hand-written — left alone, message already printed above
  *)
    ok "bin/config.toml generated for provider: ${result}"
    ;;
esac

step "Enabling the SDLC worker"
if [[ -f bin/ainxt && -f bin/config.toml ]]; then
  "${COMPOSE[@]}" up -d --build sdlc-worker \
    && ok "sdlc-worker started" \
    || warn "sdlc-worker failed to start — check: ${COMPOSE[*]} logs sdlc-worker"
else
  warn "SDLC stays disabled until both bin/ainxt and bin/config.toml exist."
fi

if [[ -n "$MODELS_DEFAULTED" ]]; then
  say ""
  warn "Claude model IDs were pre-filled with defaults, not detected from your account:"
  warn "  CLAUDE_PRIMARY_MODEL / CLAUDE_HAIKU = claude-sonnet-4-6, CLAUDE_OPUS_MODEL = claude-opus-4-7"
  warn "These are placeholders — they may not match what your Anthropic account/key can actually"
  warn "call. Check .env, correct them if needed, then apply the change with:"
  warn "  ${COMPOSE[*]} restart gateway sdlc-worker"
fi
say ""
